### ISSUE TITLE
Demo Project Alpha Split doesn't work if body selected before called

### ISSUE THREAD

**Issue by trootcode** [Weingartner/SolidworksAddinFramework#13] opened 2016-06-10 07:35 UTC
In the test project if you select a part body before calling Alpha Split then the body is listed in the Selections List but changing the Alpha value doesn't graphically show a split body and when you commit the body is not split.

**Comment by johannesegger** [comment] 2016-06-10 08:46
Sorry, I can't reproduce this one.

`MacroFeaturePropertyManagerPageBase.PushSelections` suspends the current selection list which is resumed as soon as the PMP is closed.
So as soon as you open the PMP any selection that you made before should be suspended. But this doesn't work for you?

**Comment by trootcode** [comment] 2016-06-10 18:53
Maybe your not selecting a body?  Here is a screencast showing how I do it: https://www.dropbox.com/s/druypuixn7jwppi/preselected%20bodies%20bug.webm?dl=0

**Comment by johannesegger** [comment] 2016-06-13 07:29
Ahh, you're right, I just selected a face. 9a0eda6 fixed it. Thanks for spotting. Please also verify that it works for you and if so please close the issue.

**Comment by trootcode** [comment] 2016-06-13 15:34
Yes.  That worked!

**Comment by johannesegger** [comment] 2016-06-14 04:00
Super. I'll close this then. Thanks.

**Closed as completed** 2016-06-14 04:00 UTC
